//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbentity.toolstrackingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu_Info
    {
        public long MenuID { get; set; }
        public string MenuName { get; set; }
        public string GroupCode { get; set; }
        public string NavigationTitle { get; set; }
        public Nullable<int> MenuICON { get; set; }
        public string IsMain { get; set; }
        public string ShortKey { get; set; }
        public string FileName { get; set; }
        public string AddTools { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public string IsActive { get; set; }
    }
}
