//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbentity.toolstrackingsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User_Role
    {
        public string RoleCode { get; set; }
        public string MenuID { get; set; }
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
